version: '2'
services:
    test_application:
        image: ben/data_application
        volumes:
            - /xxx/Test-Docker-Sf/Symfony:/var/www/html
    test_data:
        image: ben/data_sql
        volumes:
            - /xxx/Test-Docker-Sf/Data:/var/lib/mysql
    test_database:
        image: ben/sql
        ports:
            - 60001:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes_from:
            - test_data
    test_phpmyadmin:
        image: ben/phpmyadmin
        ports:
            - 60002:80
        links:
            - test_database:db
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
    test_web:
        image: ben/php_apache
        ports:
            - 60000:80
        environment:
            XDEBUG_CONFIG: remote_host=172.22.0.1
        volumes_from:
            - test_application
        links:
            - test_database
        working_dir: /var/www/html
