version: '2'
services:
    test_application:
        container_name: test_application
        image: ben/data_application
        volumes:
            - /home/ben/idlegame/Symfony:/var/www/html
    test_data:
        container_name: test_data
        image: ben/data_sql
        volumes:
            - /home/ben/idlegame/Data:/var/lib/mysql
    test_database:
        container_name: test_database
        image: ben/sql
        ports:
            - 60001:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes_from:
            - test_data
    test_phpmyadmin:
        container_name: test_phpmyadmin
        image: ben/phpmyadmin
        ports:
            - 60002:80
        links:
            - test_database:db
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root
    test_php:
        container_name: test_php
        image: ben/php-fpm:7.0
        volumes_from:
            - test_application
    test_web:
        container_name: test_web
        image: ben/apache
        ports:
            - 60000:80
        environment:
            FPM_HOST: test_php:9000
            XDEBUG_CONFIG: remote_host=172.22.0.1
        volumes_from:
            - test_application
        links:
            - test_database
            - test_php
